import remittence
import getvisa
import Accommodation
import airportpickup
import flightticket
import forex
import freeonlinecoureses
import guarantor
import health_insurance
import international_sim
import jobsearch
import luagage_storage
import roomessentials
import room_replacement
import studentbankaccount
import studentfinancing
import studentinternship
import travel_insurance

flightticket
airportpickup
remittence
Accommodation
getvisa
forex
freeonlinecoureses
guarantor
health_insurance
international_sim
jobsearch
luagage_storage
roomessentials
room_replacement
studentbankaccount
studentfinancing
studentinternship
travel_insurance

